### ISSUE TITLE
training failed

### ISSUE THREAD

**Issue by pipipopo** [lukedeo/keras-acgan#1]
![plot_epoch_049_generated](https://cloud.githubusercontent.com/assets/3747677/21080588/cb0c2e96-bfed-11e6-808f-6158dd577afb.png)
The training is not successful. 
generator (train)      | 2.40 | 0.54            | 1.86
generator (test)       | 2.34 | 0.52            | 1.81
discriminator (train)  | 2.86 | 0.78            | 2.09
discriminator (test)   | 2.85 | 0.79            | 2.06
Epoch 40 of 50
I use theano 0.8.2 and keras 1.0.6. I read the code and cannot find what's wrong. Any suggestion?

**Comment by lukedeo** [comment]
Can you try with `tensorflow >= 10.X` or `Theano >= 0.9.X` and a newer Keras (i.e., `>=1.1.X`)? I've seen no trouble there.

**Comment by brettbj** [comment]
@pipipopo I had all black images with a similar version of Theano, up to date versions of tensorflow and keras fixed the issue

**Comment by lukedeo** [comment]
great to hear!

**Comment by musafirsafwan** [comment]
I am also getting black images and the model is not getting trained. Updating tensorflow and keras to the latest version didn't fix the issue. I have opened a new issue since I cannot re-open this issue.
