### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by cadupont23** [lukedeo/keras-acgan#11]
Hello,

I am wondering which versions of Keras, TensorFlow and other backends this implementation uses.
Any help would be much appreciated!

**Comment by lukedeo** [comment]
Heh, great question! Haven't run this in a while - are you having issues with a specific version? If so, I can try to nail that down.

**Comment by cadupont23** [comment]
Thanks for getting back so quickly!
I'm running:
                      tensorflow 1.11.0
                      keras          2.2.4

**Comment by lukedeo** [comment]
What part is breaking / what's the error that is raised? I can try to narrow down from there.

**Comment by charlesaugdupont** [comment]
I am trying to run code from mnist_acgan.py.

<img width="771" alt="screen shot 2018-10-14 at 13 26 18" src="https://user-images.githubusercontent.com/35582936/46921831-e2be8600-cfb4-11e8-9592-4312ec28a295.png">

**Comment by charlesaugdupont** [comment]
Changed line 83 to `h = Multiply([latent, cls])`, and imported Multiply from keras.
