### ISSUE TITLE
Incorrect Shape in the python notebook predict

### ISSUE THREAD

**Issue by recluze** [lukedeo/keras-acgan#2]
I got the training working fine with the script. When loading the model for prediction, I get the following error: 

`ValueError: Error when checking : expected input_1 to have 2 dimensions, but got array with shape (100, 1, 1)`

For line: 

`generated_images = g.predict([noise, sampled_labels], verbose=0)`

I'm on the git version of theano and latest of keras (using theano backend, of course).

**Comment by recluze** [comment]
Hnn, I guess it's a typo since in `mnist_acgan.py`, we have `sampled_labels = np.array([[i] * 10 for i in range(10)]).reshape(-1, 1)`?

**Comment by lukedeo** [comment]
Ah yes, I updates the script itself but not the ipynb. Feel like opening a PR?

**Comment by recluze** [comment]
Sure. I'll send one ASAP.
